import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, writeFileSync, renameSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'
import { collectLocalChangeFacts, listLocalGitRefs } from './integrations/git/local-git'

test('本地三次提交固定 SHA、非连续 patch、重命名与 dirty 保护', async t => {
  const root = mkdtempSync(join(tmpdir(), 'quality-ai-local-git-'))
  t.after(() => rmSync(root, { recursive: true, force: true }))
  const git = (...args: string[]) => execFileSync('git', args, { cwd: root, encoding: 'utf8' }).trim()
  git('init', '-b', 'main'); git('config', 'user.name', 'Fixture'); git('config', 'user.email', 'fixture@example.invalid')
  const commit = (message: string) => { git('add', '.'); git('commit', '-m', message); return git('rev-parse', 'HEAD') }
  writeFileSync(join(root, '组件.txt'), '原始组件\n')
  const base = commit('基线')
  git('branch', 'baseline')
  writeFileSync(join(root, '组件.txt'), '重构组件\n')
  const first = commit('重构组件')
  writeFileSync(join(root, '页面.txt'), '使用组件\n')
  const second = commit('更新调用页面')
  renameSync(join(root, '组件.txt'), join(root, '组件 新.txt'))
  writeFileSync(join(root, 'binary.bin'), Buffer.from([0, 1, 2, 0]))
  const third = commit('重命名与二进制资源')
  writeFileSync(join(root, '页面.txt'), '用户尚未提交的编辑\n')
  const status = git('status', '--porcelain')
  git('update-ref', 'refs/remotes/origin/remote-only', third)
  assert.deepEqual(await listLocalGitRefs(root), { branches: [{ name: 'baseline', sha: base }, { name: 'main', sha: third }], truncated: false })
  const endpoints = await collectLocalChangeFacts(root, { mode: 'endpoints', baseRef: 'baseline', targetRef: 'main' })
  assert.equal(endpoints.targetSha, third)
  assert.equal(endpoints.effectiveBaseSha, base)
  assert.deepEqual(endpoints.commits.map(item => item.sha), [first, second, third])
  assert.equal(endpoints.dirty, true)
  assert.ok(!endpoints.diffs[0]!.patch.includes('用户尚未提交'))
  const selected = await collectLocalChangeFacts(root, { mode: 'selected_commits', targetRef: 'main', commits: [third, first] })
  assert.deepEqual(selected.commits.map(item => item.sha), [first, third])
  assert.deepEqual(selected.omittedCommitShas, [second])
  assert.deepEqual(selected.diffs[1]!.files.find(file => file.status.startsWith('R')), { status: 'R100', oldPath: '组件.txt', path: '组件 新.txt' })
  assert.match(selected.diffs[1]!.patch, /Binary files/)
  assert.equal(git('status', '--porcelain'), status)
  assert.equal(git('branch', '--show-current'), 'main')
  git('branch', '-f', 'baseline', second)
  assert.equal(endpoints.effectiveBaseSha, base, '分支移动不修改已采集事实')
  const empty = await collectLocalChangeFacts(root, { mode: 'endpoints', baseRef: third, targetRef: third })
  assert.equal(empty.diffs[0]!.files.length, 0)
  assert.ok(empty.warnings.some(value => value.includes('无可分析')))
  await assert.rejects(collectLocalChangeFacts(root, { mode: 'selected_commits', targetRef: 'main', commits: [first, first] }), /重复/)
  await assert.rejects(collectLocalChangeFacts(root, { mode: 'endpoints', baseRef: '--help', targetRef: 'main' }))
  await assert.rejects(collectLocalChangeFacts(root, { mode: 'endpoints', baseRef: 'main~1', targetRef: 'main' }))
  await assert.rejects(collectLocalChangeFacts(root, { mode: 'endpoints', baseRef: 'https://example.invalid/repo', targetRef: 'main' }))
})

test('分叉分支使用公共基线，拒绝不可达指定提交与合并提交', async t => {
  const root = mkdtempSync(join(tmpdir(), 'quality-ai-git-branches-'))
  t.after(() => rmSync(root, { recursive: true, force: true }))
  const git = (...args: string[]) => execFileSync('git', args, { cwd: root, encoding: 'utf8' }).trim()
  git('init', '-b', 'main'); git('config', 'user.name', 'Fixture'); git('config', 'user.email', 'fixture@example.invalid')
  writeFileSync(join(root, 'base'), 'base'); git('add', '.'); git('commit', '-m', 'base')
  const base = git('rev-parse', 'HEAD')
  git('checkout', '-b', 'feature')
  writeFileSync(join(root, 'feature'), 'feature'); git('add', '.'); git('commit', '-m', 'feature')
  git('checkout', 'main')
  writeFileSync(join(root, 'main'), 'main'); git('add', '.'); git('commit', '-m', 'main')
  const unrelated = git('rev-parse', 'HEAD')
  const facts = await collectLocalChangeFacts(root, { mode: 'merge_base', baseRef: 'main', targetRef: 'feature' })
  assert.equal(facts.effectiveBaseSha, base)
  assert.equal(facts.requestedBaseSha, unrelated)
  assert.deepEqual(facts.diffs[0]!.files.map(file => file.path), ['feature'])
  await assert.rejects(collectLocalChangeFacts(root, { mode: 'selected_commits', targetRef: 'feature', commits: [unrelated] }))
  git('merge', '--no-ff', 'feature', '-m', 'merge')
  await assert.rejects(collectLocalChangeFacts(root, { mode: 'selected_commits', targetRef: 'main', commits: [git('rev-parse', 'HEAD')] }), /合并提交/)
})
