import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'
import { createServer } from 'node:http'

const directory = mkdtempSync(join(tmpdir(), 'quality-ai-managed-tree-'))
process.env.QUALITY_AI_DATA_ROOT = directory
process.env.QUALITY_AI_DATABASE_PATH = join(directory, 'db.sqlite')
process.env.PROJECTS_CONFIG_PATH = join(directory, 'projects.json')
const root = join(directory, 'project'); mkdirSync(root)
writeFileSync(process.env.PROJECTS_CONFIG_PATH, JSON.stringify({ projects: [{ id: 'fixture', name: '公开示例', root }] }))
const { database } = await import('./storage/database')
const { initializeChangeSets, previewChangeSet, freezeChangeSet } = await import('./modules/regressions/change-sets')
const { initializeManagedWorktrees, acquireChangeSetWorktree, releaseChangeSetWorktree, removeUnusedChangeSetWorktree } = await import('./integrations/git/worktree-manager')
const { analyzeChangeSetSource } = await import('./modules/regressions/source-impact')
const { handleRegressionRoutes } = await import('./modules/regressions/routes')

test('独立 detached 快照固定版本、复用引用并保护原工作区及脏快照', async t => {
  t.after(() => { database.close(); rmSync(directory, { recursive: true, force: true }) })
  const git = (...args: string[]) => execFileSync('git', args, { cwd: root, encoding: 'utf8' }).trim()
  git('init', '-b', 'main'); git('config', 'user.name', 'Fixture'); git('config', 'user.email', 'fixture@example.invalid')
  writeFileSync(join(root, 'page.ts'), 'base'); git('add', '.'); git('commit', '-m', 'base')
  const base = git('rev-parse', 'HEAD')
  git('checkout', '-b', 'refactor')
  writeFileSync(join(root, '.gitattributes'), '*.ts filter=fixture\n')
  writeFileSync(join(root, 'page.ts'), 'target'); git('add', '.'); git('commit', '-m', 'target')
  const target = git('rev-parse', 'HEAD')
  git('checkout', 'main')
  writeFileSync(join(root, 'page.ts'), 'unsaved user changes')
  const originalStatus = git('status', '--porcelain')
  initializeChangeSets(); initializeManagedWorktrees()
  const preview = await previewChangeSet({ projectId: 'fixture', comparison: { mode: 'endpoints', baseRef: base, targetRef: 'refactor' } })
  await assert.rejects(acquireChangeSetWorktree(preview.id, 'before confirmation'), /先确认/)
  freezeChangeSet(preview.id, preview.factsHash)
  const api=createServer(async(request,response)=>{if(!await handleRegressionRoutes(request,response)){response.writeHead(404);response.end()}})
  await new Promise<void>(resolve=>api.listen(0,'127.0.0.1',resolve))
  t.after(()=>new Promise<void>(resolve=>{api.closeAllConnections();api.close(()=>resolve())}))
  const address=api.address();assert.ok(address&&typeof address!=='string')
  const endpoint=`http://127.0.0.1:${address.port}/api/change-sets/${preview.id}/worktree`
  const status=async()=>(await(await fetch(endpoint)).json()).worktree
  const remove=(body:unknown)=>fetch(endpoint+'/remove',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})
  assert.equal((await status()).state,'not_created')
  git('config', 'filter.fixture.smudge', 'false')
  git('config', 'filter.fixture.required', 'true')
  const [first, second] = await Promise.all([acquireChangeSetWorktree(preview.id, 'analysis'), acquireChangeSetWorktree(preview.id, 'execution')])
  assert.equal(first.path, second.path)
  assert.notEqual(first.token, second.token)
  assert.equal(first.sha, target)
  assert.equal((await status()).references.length,2)
  assert.equal((await status()).canRemove,false)
  assert.equal((await remove({confirmed:true,expectedSha:target})).status,409)
  const impact = await analyzeChangeSetSource(preview.id, 'source-impact')
  assert.ok(impact.trees.some(tree => tree.sha === target && tree.scannedFiles.includes('page.ts')))
  assert.equal((database.prepare('SELECT count(*) AS count FROM regression_worktree_leases').get() as { count: number }).count, 2, '分析完成释放自己的引用，保留其他任务引用')
  assert.equal(readFileSync(join(first.path, 'page.ts'), 'utf8'), 'target')
  assert.equal(execFileSync('git', ['rev-parse', '--abbrev-ref', 'HEAD'], { cwd: first.path, encoding: 'utf8' }).trim(), 'HEAD')
  assert.equal(git('branch', '--show-current'), 'main')
  assert.equal(git('status', '--porcelain'), originalStatus)
  assert.equal(readFileSync(join(root, 'page.ts'), 'utf8'), 'unsaved user changes')
  git('branch', '-f', 'refactor', base)
  assert.equal(execFileSync('git', ['rev-parse', 'HEAD'], { cwd: first.path, encoding: 'utf8' }).trim(), target)
  await assert.rejects(removeUnusedChangeSetWorktree(preview.id), /引用/)
  releaseChangeSetWorktree(first.token); releaseChangeSetWorktree(first.token)
  await assert.rejects(removeUnusedChangeSetWorktree(preview.id), /引用/)
  releaseChangeSetWorktree(second.token)
  writeFileSync(join(first.path, 'extra.txt'), 'must preserve')
  assert.equal((await status()).canRemove,false)
  assert.match((await status()).reason,/额外文件/)
  await assert.rejects(acquireChangeSetWorktree(preview.id, 'new analysis'), /额外文件/)
  await assert.rejects(removeUnusedChangeSetWorktree(preview.id), /额外文件/)
  assert.equal(readFileSync(join(first.path, 'extra.txt'), 'utf8'), 'must preserve')
  rmSync(join(first.path, 'extra.txt'))
  assert.equal((await status()).canRemove,true)
  assert.equal((await remove({confirmed:true,expectedSha:base})).status,409)
  assert.equal((await remove({expectedSha:target})).status,409)
  assert.equal((await remove({confirmed:true,expectedSha:target})).status,200)
  assert.equal((await status()).state,'removed')
  assert.equal(existsSync(first.path), false)
  assert.equal(readFileSync(join(root, 'page.ts'), 'utf8'), 'unsaved user changes')
  await assert.rejects(removeUnusedChangeSetWorktree('not-owned'), /没有平台登记/)
  const restored = await acquireChangeSetWorktree(preview.id, 'later analysis')
  assert.equal(readFileSync(join(restored.path, 'page.ts'), 'utf8'), 'target', '清理后仍从旧 SHA 恢复，不追随新分支')
  releaseChangeSetWorktree(restored.token)
  await removeUnusedChangeSetWorktree(preview.id)
})
